volumes:
  db:
  
services:
  db:
    container_name: postgres
    image: postgres:16.4
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
      POSTGRES_DB: sandbox
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
networks:
  db:
    driver: bridge
